[package]
name = "dir2df2sql"
version = "0.1.0"
edition = "2024"

[dependencies.rs-dir2df2sql]
path = "../.."

[dependencies.tokio]
version = "1"
default-features = false
features = [
	"macros",
	"rt-multi-thread",
]

